#!/bin/bash

stash_local_changes() {
    echo "Stashing local changes"

    git stash -q --keep-index -u
}

run_ktlint_and_add_to_staging(){
    echo "Running Ktlint"
    ./gradlew ktlintFormat -q

    git add .

    ./gradlew ktlintCheck -q
}

check_for_ktLint_error(){
    ktLintStatus=$?

    if [[ $ktLintStatus -ne 0 ]]; then
        echo "ktLint failed"
        echo "Pop Stash"
#        git stash pop -q
        exit $ktLintStatus
    fi
}

run_tests() {
    echo "Running unit tests"
    ./gradlew test
}

restore_stash() {
    echo "Pop Stash"
    git stash pop -q
}

#stash_local_changes

run_ktlint_and_add_to_staging

check_for_ktLint_error

run_tests

status=$?

#restore_stash

exit $status


