micronaut:
  application:
    name: sleepermanager

external:
  api:
    sleeper:
      user:
        root: https://api.sleeper.app/v1/user
        getByUsername: /{username}
        getLeagues: /{userId}/leagues/nfl/2020
      roster: https://api.sleeper.app/v1/league/<league_id>/rosters
      player: https://api.sleeper.app/v1/players/nfl
