datasources:
  default:
    url: jdbc:postgresql://db:5432/sleeper_manager
    driverClassName: org.postgresql.Driver
    username: sa
    password: sa
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
