micronaut:
  application:
    name: sleepermanager

external:
  api:
    sleeper:
      base: https://api.sleeper.app/v1
      user:
        root: ${external.api.sleeper.base}/user
        getByUsername: /{username}
        getLeagues: /{userId}/leagues/nfl/2020
      roster: ${external.api.sleeper.base}/league/{leagueId}/rosters
      player: ${external.api.sleeper.base}/players/nfl
