micronaut:
  application:
    name: sleepermanager
  http:
    client:
      read-timeout: 30s
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    host: 0.0.0.0
    thread-selection: auto

mongodb:
  uri: mongodb://username:password@localhost:27017/databaseName

external:
  api:
    sleeper:
      base: https://api.sleeper.app/v1
      user:
        root: ${external.api.sleeper.base}/user
        getByUsername: /{username}
        getLeagues: /{userId}/leagues/nfl/2020
      roster: ${external.api.sleeper.base}/league/{leagueId}/rosters
      player: ${external.api.sleeper.base}/players/nfl
